source-file ~/dotfiles/.config/tmux/tmux.reset.conf
set-option -g default-terminal 'screen-254color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 30000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g default-terminal "${TERM}"
set -g allow-passthrough on
set -ga update-environment "${TERM}"
set -ga update-environment "${TERM_PROGRAM}"

# Toggle tmux status bar
bind 'h' set status
if-shell "[[ $(tmux lsw | wc -l) -le 1 ]]" 'set -g status'

# tmux enable mouse
set -g mouse on

bind-key -r i run-shell "tmux neww ~/.local/bin/scripts/tmux-cht.sh"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'tmux-plugins/minimal-tmux-status'

set -g status on
set -g @session-wizard 'o'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

run '~/.tmux/plugins/tpm/tpm'
