# Keyboard Layout and Repeat Rate
xkb_rules_layout=us,ara
xkb_rules_options=grp:alt_shift_toggle
repeat_rate=35
repeat_delay=200
numlockon=1

# Touchpad
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0

# Mouse
mouse_natural_scrolling=0

# Focus
sloppyfocus=1
warpcursor=1
focus_on_activate=1
