return {
  -- "neovim/nvim-lspconfig",
  -- opts = {
  --   servers = {
  --     racket_langserver = {
  --       cmd = { "racket", "--lib", "racket-langserver" },
  --       filetypes = { "racket", "scheme" },
  --       root_dir = function(fname)
  --         local util = require("lspconfig.util")
  --         return util.root_pattern(".git")(fname) or vim.fn.getcwd()
  --       end,
  --       settings = {
  --         ["racket-langserver"] = {
  --           completion = true,
  --           documentation = true,
  --           format = true,
  --           hover = true,
  --         },
  --       },
  --     },
  --   },
  -- },
}
