return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "html",
      "javascript",
      "astro",
      "vue",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "prisma",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "php",
      "templ",
    },
  },
}
